<a href="https://colab.research.google.com/github/immazenam/test/blob/master/R%EA%B3%BC_%ED%8C%8C%EC%9D%B4%EC%8D%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2 장

In [1]:
2+3/2

3.5

In [2]:
2**10

1024

In [3]:
a=10
a

10

In [4]:
print(a)

10


In [5]:
a*2+3

23

In [6]:
a=100
print(type(a))
b=100.1
print(type(b))

<class 'int'>
<class 'float'>


In [7]:
bool(23.7)

True

In [8]:
bool(0)

False

In [9]:
c = 'my string'
d = str(a)+" "+c
print(d)
print(int(b))

100 my string
100


In [10]:
bool('')

False

In [11]:
import numpy as np
a = np.arange(15)
print(a)
m = np.mean(a)
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
7.0


In [12]:
height = np.array([45, 75, 60, 51, np.nan])
print(np.mean(height))
print(np.nanmean(height))

nan
57.75


In [13]:
x = np.array([1, -1, 0, np.infty, -np.inf])
print(x/0)
print(x/np.Infinity)

[ inf -inf  nan  inf -inf]
[ 0. -0.  0. nan nan]


<ipython-input-13-11678b3c65f9>:2: RuntimeWarning: divide by zero encountered in divide
  print(x/0)
<ipython-input-13-11678b3c65f9>:2: RuntimeWarning: invalid value encountered in divide
  print(x/0)
<ipython-input-13-11678b3c65f9>:3: RuntimeWarning: invalid value encountered in divide
  print(x/np.Infinity)


In [14]:
import datetime as dt
now = dt.datetime.now()
print(now.year)

2024


In [15]:
print(now.strftime("%Y-%m-%d: %A"))

2024-10-12: Saturday


In [16]:
dob1 = dt.datetime(2000, 5, 17)
age = now.year - dob1.year
print(age)

24


# 3 장

In [17]:
xv = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
xv = np.arange(1,10)
xv[4]

5

In [18]:
xv[1:4]

array([2, 3, 4])

In [19]:
len(xv)

9

In [20]:
xv.size

9

In [21]:
xm=np.array([[1,2,3], [4,5,6], [7,8,9]])
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
xm = np.arange(1,10)
xm = xm.reshape(3,3)
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
xm = np.array(range(1,10))
xm = xm.reshape(3,3)
xm.shape

(3, 3)

In [24]:
xm[1,2]

6

In [25]:
xm[:, 0]

array([1, 4, 7])

In [26]:
xm[0:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
xv[3] = 11
xv

array([ 1,  2,  3, 11,  5,  6,  7,  8,  9])

In [28]:
xm[0,2] = 11
xm

array([[ 1,  2, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
a = [2,3,'c']
x= [1,2,'a', a]
print(x)

[1, 2, 'a', [2, 3, 'c']]


In [30]:
x[3]

[2, 3, 'c']

In [31]:
x2 = [[1,2,3], [4,5,6], [7,8,9]]
x2[0][2]

3

In [32]:
x2[2]

[7, 8, 9]

In [33]:
[row[2] for row in x2]

[3, 6, 9]

In [34]:
tpl = (1,2,3)
type(tpl)

tuple

In [35]:
tpl[2]

3

In [36]:
country_code = {'korea':82, 'us':1, 'china':86}
print(len(country_code))

3


In [37]:
print(country_code['korea'])

82


In [38]:
print(country_code.keys())

dict_keys(['korea', 'us', 'china'])


In [39]:
print(country_code.values())

dict_values([82, 1, 86])


In [40]:
print(country_code.items())

dict_items([('korea', 82), ('us', 1), ('china', 86)])


In [41]:
xm2 = xm
xm2 = xm.copy()
xm[0][0] = 10

In [42]:
from copy import deepcopy
ym= [[1,2,3], [4,5,6], [7,8,9]]
ym2 = deepcopy(ym)
ym[0][0] = 10
print(ym2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [43]:
import pandas as pd
import numpy as np
d={'name':['Kim', 'Lee', 'Park'], 'height': [170, 180, 175]}
df1 = pd. DataFrame(data=d)
print(df1)

   name  height
0   Kim     170
1   Lee     180
2  Park     175


In [44]:
df2 = pd.DataFrame([['Kim', 170], ['Lee', 180], ['Pakr', 175]], columns=['name', 'height'])
print(df2)

   name  height
0   Kim     170
1   Lee     180
2  Pakr     175


In [45]:
df3 = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]),
                   columns=['a', 'b', 'c'])
print(df3)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9


In [46]:
print(df3.describe())

         a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0


In [47]:
x = df1['height']
print(x)

0    170
1    180
2    175
Name: height, dtype: int64


In [48]:
y = df1.iloc[0:2]
print(y)

  name  height
0  Kim     170
1  Lee     180


In [49]:
y = df1.iloc[:, 1]
print(y)

0    170
1    180
2    175
Name: height, dtype: int64


In [50]:
y = df1.iloc[:, -1]
print(y)

0    170
1    180
2    175
Name: height, dtype: int64


In [51]:
y = df1.iloc[[1,2], 0]
print(y)

1     Lee
2    Park
Name: name, dtype: object


In [52]:
x1 = [1,2,3,4]; x2 = [5,6,7,8]
y1 = np.array([1,2,3,4]); y2 = np.array([5,6,7,8])
print(x1+[2])

[1, 2, 3, 4, 2]


In [53]:
print(y1+2)

[3 4 5 6]


In [54]:
print(x1+x2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [55]:
print(y1+y2)

[ 6  8 10 12]


In [56]:
xrow = np.array([1,2,3])
xcol = np.array([[1], [2], [3]])
print("dimensions: ", xrow.shape, xcol.shape)

dimensions:  (3,) (3, 1)


In [57]:
print("xrow \n", xrow, "\n xcol: \n", xcol)

xrow 
 [1 2 3] 
 xcol: 
 [[1]
 [2]
 [3]]


In [58]:
aa = np.array(range(1, 11))
bb = np.array(range(1, 6))
cc = np.array([1,2,1,2,1])

In [59]:
bb +cc

array([2, 4, 4, 6, 6])

In [60]:
aa *3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [61]:
bb ** 2

array([ 1,  4,  9, 16, 25])

In [62]:
np.power(bb, 2)

array([ 1,  4,  9, 16, 25])

In [63]:
a = np.array(range(1,11,2))
print(a)

[1 3 5 7 9]


In [64]:
a1 = np.delete(a, 2)
print(a1)

[1 3 7 9]


In [65]:
idx = [0, 1, 3]
a2 = np.delete(a, idx)
print(a2)

[5 9]


In [66]:
b1 = 11
a3 = np.append(a, b1)
b2 = 2
a4 = np.insert(a, 1, b2)
print(a3)
print(a4)
b3= [1,2,3]
a5 = np.insert(a, 2, b3)
print(a5)

[ 1  3  5  7  9 11]
[1 2 3 5 7 9]
[1 3 1 2 3 5 7 9]


In [67]:
mx1 = np.array(range(1,10)).reshape(3,3)
mx2 = np.append(mx1, np.array([10, 20, 30]).reshape(1,3), axis=0)
mx3 = np.append(mx1, np.array([10, 20, 30]).reshape(3,1), axis=1)
print(mx1)
print(mx2)
print(mx3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [68]:
mx4 = np.delete(mx1, 0, axis=0)
mx5 = np.delete(mx1, [0,1], axis=1)
print(mx4)
print(mx5)

[[4 5 6]
 [7 8 9]]
[[3]
 [6]
 [9]]


In [69]:
mx6 = np.insert(mx1, 1, np.array([10, 20, 30]), axis=0)
mx7 = np.insert(mx1, 1, np.array(range(10, 100, 10)).reshape(3,3), axis=1)
print(mx6)
print(mx7)

[[ 1  2  3]
 [10 20 30]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10 40 70  2  3]
 [ 4 20 50 80  5  6]
 [ 7 30 60 90  8  9]]


In [70]:
mtx = np.array([[1,2,3], [4,5,6]])
mtx

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
mtx = np.array([1,2,3,4,5,6]).reshape(2,3)
mtx

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
mx1 = np.array(range(1,7)).reshape(2,3)
mx2 = np.hstack((np.repeat(1,3).reshape(3,1), np.repeat(2,3).reshape(3,1)))
print(mx1)
print(mx2)
mx3 = np.matmul(mx1, mx2)
print(mx3)
mx3.shape

[[1 2 3]
 [4 5 6]]
[[1 2]
 [1 2]
 [1 2]]
[[ 6 12]
 [15 30]]


(2, 2)

# 4 장

In [73]:
def if_test1 (x):
    if (x % 2 ==  0):
        print(x, "는 짝수입니다")
    else:
        if (x % 2 == 1):
            print(x, "는 홀수입니다")
        else:
            print(x, "는 자연수가 아닙니다")
if_test1(8)

8 는 짝수입니다


In [74]:
def if_test2 (x):
    if(x % 2 == 0):
        print(x, "는 짝수입니다")
    elif(x % 2 == 1):
        print(x, "는 홀수입니다")
    else:
        print(x, "는 자연수가 아닙니다")
if_test2(7)

7 는 홀수입니다


In [75]:
mysum = 0
for x in [1,2,3,4,5,6,7,8,9,10]:
    mysum = mysum + x**2
else:
    print(mysum)

385


In [76]:
x = 1
sum1 = 0
while (x <= 10):
    sum1 = sum1 + x**2
    x = x + 1
#else: else가 있다면 print(sum1)은 들여써야함.
print(sum1)

385


In [77]:
x = range(1,6)
for j in x:
    if (j==3): continue
    print(j, " ")

1  
2  
4  
5  


In [78]:
x = range(1,6)
for j in x:
    if (j==3): break
    print(j, " ")

1  
2  


In [79]:
def sum2(x, y):
    mysum = x + y
    return mysum
sum2(4,7)

11

In [80]:
def my_sums(a=0, b=10):
    sum1 = 0; sum2 = 0
    data = np.arange(a,b+1)
    for i in data:
        sum1 = sum1 + i
        sum2 = sum2+ i**2
    return sum1, sum2, len(data)
my_sums()

(55, 385, 11)

In [81]:
a = my_sums(1,10)
mm = a[0]/a[2]
vv = (a[1] - a[2]*(mm**2))/(a[2] -1)
print(mm) #평균
print(vv) #분산

5.5
9.166666666666666


In [82]:
class Student:
    def __init__(self, first, last):
        self.first = first
        self.last = last

    def capital_first(self):
        return self.first.upper()
aa = Student('John', 'Doe')
bb = Student('Jane', 'Doe')
print(aa.first, aa.last)
print(bb.first, bb.last)
print(aa.capital_first(), bb.capital_first())

John Doe
Jane Doe
JOHN JANE


In [83]:
class StudentGrade(Student):
    def __init__(self, first, last, score):
        super().__init__(first, last)
        self.score = score
    def grade(self):
        if self.score < 80:
            grade = 'B'
        else:
            grade = 'A'
        return grade

In [84]:
aa = StudentGrade('John', 'Doe', 75)
bb = StudentGrade('Jane', 'Doe', 95)
print(aa.first, aa.last)
print(aa.score, aa.grade())
print(bb.score, bb.grade())
print(bb.capital_first())

John Doe
75 B
95 A
JANE


In [85]:
def __init__(self, first, last, scroe):
    self.first = first
    self.last = last
    self.score = score

In [86]:
aa = StudentGrade('John', 'Doe', 75)
bb = StudentGrade('Jane', 'Doe', 95)
print(aa.first, aa.last)
print(aa.score, aa.grade())
print(bb.score, bb.grade())
print(bb.capital_first())

John Doe
75 B
95 A
JANE


# 5 장

In [87]:
import datetime
def birthyear():
    age = input("Enter age: ")
    now = datetime.datetime.now()
    curyear = now.year
    b_year = curyear - int(age)
    print("born.year= ", b_year)
birthyear()

Enter age: 50
born.year=  1974


In [88]:
from pandas import DataFrame
cars = {'make': ['Hyundai', 'Kia', 'Ford', 'Chevrole'],
        'model': ['Sonata', 'K5', 'Taurus', 'Impala'],
        'price': [3200,3100,3500,3700]}
df = pd.DataFrame(cars)
write_txt = df.to_csv('cars.txt', sep=" ", index=True, header=True)

In [89]:
f = open('cars.txt',"w")
write_csv = df.to_csv(f, sep=" ", index=None, header=True)
f.close()

In [97]:
from google.colab import files
uploaded = files.upload()

Saving height.xlsx to height.xlsx


In [98]:
data = pd.read_excel('height.xlsx', header=None,
                     names=['height', 'gender'])
df1= pd.DataFrame(data)
df1

height gender
0     170      M
1     175      M
2     182      M
3     168      F
4     162      F
5     158      F

In [95]:
cars = {'make': ['Hyundai', 'Kia', 'Ford', 'Chevrolet'],
        'model': ['Sonata', 'K5', 'Taurus', 'Impala'],
        'price': [3200,3100,3500,3700]}
df3 = pd.DataFrame(cars)
export_excel = df3.to_excel('cars.xlsx', index=None, header=True)

In [100]:
a = "abc"
print(len(a))
print(a[1])

3
b


In [101]:
x,y,z = a
print(x)

a


In [102]:
bb = 'A test string'
blist0 = bb.split()
blist1 = bb.split('i')
print(blist0, blist1)

['A', 'test', 'string'] ['A test str', 'ng']


In [103]:
aa = a + "ABC"
print(aa)

abcABC


In [104]:
aaa = a*3
print(aaa)

abcabcabc


In [105]:
mystr = 'abcdeabcab'
n0 = mystr.count('ab')
n1 = mystr.find('ab')
n2 = mystr.rfind('ab')
newstr = mystr.replace('ab', 'AB')
print(n0, n1, n2, newstr)

3 0 8 ABcdeABcAB


In [106]:
import re
mystr = re.sub('\\[','A', '[12.5+13-1*5$')
print(mystr)

A12.5+13-1*5$


In [107]:
mtstr = re.sub('[a-z]', '-', 'bcde0123ABC')
print(mtstr)

----0123ABC


In [109]:
l_case = re.search('[a-z]', 'bcde0123ABC')
if l_case: print('a-z exits')
else: print('No a-z')

a-z exits


In [111]:
l_case = re.search('[k-z]', 'bcde0123ABC')
if l_case: print('k-z exits')
else: print('No k-z')

No k-z


In [116]:
mystr = [re.sub('grey|gray', 'GRAY',word) for word in ['grey', 'gray', 'groy', 'greay', 'greey']]
print(mystr)

['GRAY', 'GRAY', 'groy', 'greay', 'greey']


In [117]:
mystr = [re.sub('gr(e|a)y', 'GRAY',word) for word in ['grey', 'gray', 'groy', 'greay', 'greey']]
print(mystr)

['GRAY', 'GRAY', 'groy', 'greay', 'greey']
