<a href="https://colab.research.google.com/github/immazenam/test/blob/master/R%EA%B3%BC_%ED%8C%8C%EC%9D%B4%EC%8D%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2 장

In [119]:
2+3/2

3.5

In [120]:
2**10

1024

In [121]:
a=10
a

10

In [122]:
print(a)

10


In [123]:
a*2+3

23

In [124]:
a=100
print(type(a))
b=100.1
print(type(b))

<class 'int'>
<class 'float'>


In [125]:
bool(23.7)

True

In [126]:
bool(0)

False

In [127]:
c = 'my string'
d = str(a)+" "+c
print(d)
print(int(b))

100 my string
100


In [128]:
bool('')

False

In [129]:
import numpy as np
a = np.arange(15)
print(a)
m = np.mean(a)
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
7.0


In [130]:
height = np.array([45, 75, 60, 51, np.nan])
print(np.mean(height))
print(np.nanmean(height))

nan
57.75


In [131]:
x = np.array([1, -1, 0, np.infty, -np.inf])
print(x/0)
print(x/np.Infinity)

[ inf -inf  nan  inf -inf]
[ 0. -0.  0. nan nan]


<ipython-input-131-11678b3c65f9>:2: RuntimeWarning: divide by zero encountered in divide
  print(x/0)
<ipython-input-131-11678b3c65f9>:2: RuntimeWarning: invalid value encountered in divide
  print(x/0)
<ipython-input-131-11678b3c65f9>:3: RuntimeWarning: invalid value encountered in divide
  print(x/np.Infinity)


In [132]:
import datetime as dt
now = dt.datetime.now()
print(now.year)

2024


In [133]:
print(now.strftime("%Y-%m-%d: %A"))

2024-10-19: Saturday


In [134]:
dob1 = dt.datetime(2000, 5, 17)
age = now.year - dob1.year
print(age)

24


# 3 장

In [135]:
xv = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
xv = np.arange(1,10)
xv[4]

5

In [136]:
xv[1:4]

array([2, 3, 4])

In [137]:
len(xv)

9

In [138]:
xv.size

9

In [139]:
xm=np.array([[1,2,3], [4,5,6], [7,8,9]])
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
xm = np.arange(1,10)
xm = xm.reshape(3,3)
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
xm = np.array(range(1,10))
xm = xm.reshape(3,3)
xm.shape

(3, 3)

In [142]:
xm[1,2]

6

In [143]:
xm[:, 0]

array([1, 4, 7])

In [144]:
xm[0:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
xv[3] = 11
xv

array([ 1,  2,  3, 11,  5,  6,  7,  8,  9])

In [146]:
xm[0,2] = 11
xm

array([[ 1,  2, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [147]:
a = [2,3,'c']
x= [1,2,'a', a]
print(x)

[1, 2, 'a', [2, 3, 'c']]


In [148]:
x[3]

[2, 3, 'c']

In [149]:
x2 = [[1,2,3], [4,5,6], [7,8,9]]
x2[0][2]

3

In [150]:
x2[2]

[7, 8, 9]

In [151]:
[row[2] for row in x2]

[3, 6, 9]

In [152]:
tpl = (1,2,3)
type(tpl)

tuple

In [153]:
tpl[2]

3

In [154]:
country_code = {'korea':82, 'us':1, 'china':86}
print(len(country_code))

3


In [155]:
print(country_code['korea'])

82


In [156]:
print(country_code.keys())

dict_keys(['korea', 'us', 'china'])


In [157]:
print(country_code.values())

dict_values([82, 1, 86])


In [158]:
print(country_code.items())

dict_items([('korea', 82), ('us', 1), ('china', 86)])


In [159]:
xm2 = xm
xm2 = xm.copy()
xm[0][0] = 10

In [160]:
from copy import deepcopy
ym= [[1,2,3], [4,5,6], [7,8,9]]
ym2 = deepcopy(ym)
ym[0][0] = 10
print(ym2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [161]:
import pandas as pd
import numpy as np
d={'name':['Kim', 'Lee', 'Park'], 'height': [170, 180, 175]}
df1 = pd. DataFrame(data=d)
print(df1)

   name  height
0   Kim     170
1   Lee     180
2  Park     175


In [162]:
df2 = pd.DataFrame([['Kim', 170], ['Lee', 180], ['Pakr', 175]], columns=['name', 'height'])
print(df2)

   name  height
0   Kim     170
1   Lee     180
2  Pakr     175


In [163]:
df3 = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]),
                   columns=['a', 'b', 'c'])
print(df3)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9


In [164]:
print(df3.describe())

         a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0


In [165]:
x = df1['height']
print(x)

0    170
1    180
2    175
Name: height, dtype: int64


In [166]:
y = df1.iloc[0:2]
print(y)

  name  height
0  Kim     170
1  Lee     180


In [167]:
y = df1.iloc[:, 1]
print(y)

0    170
1    180
2    175
Name: height, dtype: int64


In [168]:
y = df1.iloc[:, -1]
print(y)

0    170
1    180
2    175
Name: height, dtype: int64


In [169]:
y = df1.iloc[[1,2], 0]
print(y)

1     Lee
2    Park
Name: name, dtype: object


In [170]:
x1 = [1,2,3,4]; x2 = [5,6,7,8]
y1 = np.array([1,2,3,4]); y2 = np.array([5,6,7,8])
print(x1+[2])

[1, 2, 3, 4, 2]


In [171]:
print(y1+2)

[3 4 5 6]


In [172]:
print(x1+x2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [173]:
print(y1+y2)

[ 6  8 10 12]


In [174]:
xrow = np.array([1,2,3])
xcol = np.array([[1], [2], [3]])
print("dimensions: ", xrow.shape, xcol.shape)

dimensions:  (3,) (3, 1)


In [175]:
print("xrow \n", xrow, "\n xcol: \n", xcol)

xrow 
 [1 2 3] 
 xcol: 
 [[1]
 [2]
 [3]]


In [176]:
aa = np.array(range(1, 11))
bb = np.array(range(1, 6))
cc = np.array([1,2,1,2,1])

In [177]:
bb +cc

array([2, 4, 4, 6, 6])

In [178]:
aa *3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [179]:
bb ** 2

array([ 1,  4,  9, 16, 25])

In [180]:
np.power(bb, 2)

array([ 1,  4,  9, 16, 25])

In [181]:
a = np.array(range(1,11,2))
print(a)

[1 3 5 7 9]


In [182]:
a1 = np.delete(a, 2)
print(a1)

[1 3 7 9]


In [183]:
idx = [0, 1, 3]
a2 = np.delete(a, idx)
print(a2)

[5 9]


In [184]:
b1 = 11
a3 = np.append(a, b1)
b2 = 2
a4 = np.insert(a, 1, b2)
print(a3)
print(a4)
b3= [1,2,3]
a5 = np.insert(a, 2, b3)
print(a5)

[ 1  3  5  7  9 11]
[1 2 3 5 7 9]
[1 3 1 2 3 5 7 9]


In [185]:
mx1 = np.array(range(1,10)).reshape(3,3)
mx2 = np.append(mx1, np.array([10, 20, 30]).reshape(1,3), axis=0)
mx3 = np.append(mx1, np.array([10, 20, 30]).reshape(3,1), axis=1)
print(mx1)
print(mx2)
print(mx3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [186]:
mx4 = np.delete(mx1, 0, axis=0)
mx5 = np.delete(mx1, [0,1], axis=1)
print(mx4)
print(mx5)

[[4 5 6]
 [7 8 9]]
[[3]
 [6]
 [9]]


In [187]:
mx6 = np.insert(mx1, 1, np.array([10, 20, 30]), axis=0)
mx7 = np.insert(mx1, 1, np.array(range(10, 100, 10)).reshape(3,3), axis=1)
print(mx6)
print(mx7)

[[ 1  2  3]
 [10 20 30]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10 40 70  2  3]
 [ 4 20 50 80  5  6]
 [ 7 30 60 90  8  9]]


In [188]:
mtx = np.array([[1,2,3], [4,5,6]])
mtx

array([[1, 2, 3],
       [4, 5, 6]])

In [189]:
mtx = np.array([1,2,3,4,5,6]).reshape(2,3)
mtx

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
mx1 = np.array(range(1,7)).reshape(2,3)
mx2 = np.hstack((np.repeat(1,3).reshape(3,1), np.repeat(2,3).reshape(3,1)))
print(mx1)
print(mx2)
mx3 = np.matmul(mx1, mx2)
print(mx3)
mx3.shape

[[1 2 3]
 [4 5 6]]
[[1 2]
 [1 2]
 [1 2]]
[[ 6 12]
 [15 30]]


(2, 2)

# 4 장

In [191]:
def if_test1 (x):
    if (x % 2 ==  0):
        print(x, "는 짝수입니다")
    else:
        if (x % 2 == 1):
            print(x, "는 홀수입니다")
        else:
            print(x, "는 자연수가 아닙니다")
if_test1(8)

8 는 짝수입니다


In [192]:
def if_test2 (x):
    if(x % 2 == 0):
        print(x, "는 짝수입니다")
    elif(x % 2 == 1):
        print(x, "는 홀수입니다")
    else:
        print(x, "는 자연수가 아닙니다")
if_test2(7)

7 는 홀수입니다


In [193]:
mysum = 0
for x in [1,2,3,4,5,6,7,8,9,10]:
    mysum = mysum + x**2
else:
    print(mysum)

385


In [194]:
x = 1
sum1 = 0
while (x <= 10):
    sum1 = sum1 + x**2
    x = x + 1
#else: else가 있다면 print(sum1)은 들여써야함.
print(sum1)

385


In [195]:
x = range(1,6)
for j in x:
    if (j==3): continue
    print(j, " ")

1  
2  
4  
5  


In [196]:
x = range(1,6)
for j in x:
    if (j==3): break
    print(j, " ")

1  
2  


In [197]:
def sum2(x, y):
    mysum = x + y
    return mysum
sum2(4,7)

11

In [198]:
def my_sums(a=0, b=10):
    sum1 = 0; sum2 = 0
    data = np.arange(a,b+1)
    for i in data:
        sum1 = sum1 + i
        sum2 = sum2+ i**2
    return sum1, sum2, len(data)
my_sums()

(55, 385, 11)

In [199]:
a = my_sums(1,10)
mm = a[0]/a[2]
vv = (a[1] - a[2]*(mm**2))/(a[2] -1)
print(mm) #평균
print(vv) #분산

5.5
9.166666666666666


In [200]:
class Student:
    def __init__(self, first, last):
        self.first = first
        self.last = last

    def capital_first(self):
        return self.first.upper()
aa = Student('John', 'Doe')
bb = Student('Jane', 'Doe')
print(aa.first, aa.last)
print(bb.first, bb.last)
print(aa.capital_first(), bb.capital_first())

John Doe
Jane Doe
JOHN JANE


In [201]:
class StudentGrade(Student):
    def __init__(self, first, last, score):
        super().__init__(first, last)
        self.score = score
    def grade(self):
        if self.score < 80:
            grade = 'B'
        else:
            grade = 'A'
        return grade

In [202]:
aa = StudentGrade('John', 'Doe', 75)
bb = StudentGrade('Jane', 'Doe', 95)
print(aa.first, aa.last)
print(aa.score, aa.grade())
print(bb.score, bb.grade())
print(bb.capital_first())

John Doe
75 B
95 A
JANE


In [203]:
def __init__(self, first, last, scroe):
    self.first = first
    self.last = last
    self.score = score

In [204]:
aa = StudentGrade('John', 'Doe', 75)
bb = StudentGrade('Jane', 'Doe', 95)
print(aa.first, aa.last)
print(aa.score, aa.grade())
print(bb.score, bb.grade())
print(bb.capital_first())

John Doe
75 B
95 A
JANE


# 5 장

In [205]:
import datetime
def birthyear():
    age = input("Enter age: ")
    now = datetime.datetime.now()
    curyear = now.year
    b_year = curyear - int(age)
    print("born.year= ", b_year)
birthyear()

Enter age: 50
born.year=  1974


In [206]:
from pandas import DataFrame
cars = {'make': ['Hyundai', 'Kia', 'Ford', 'Chevrole'],
        'model': ['Sonata', 'K5', 'Taurus', 'Impala'],
        'price': [3200,3100,3500,3700]}
df = pd.DataFrame(cars)
write_txt = df.to_csv('cars.txt', sep=" ", index=True, header=True)

In [207]:
f = open('cars.txt',"w")
write_csv = df.to_csv(f, sep=" ", index=None, header=True)
f.close()

In [209]:
data = pd.read_excel('height.xlsx', header=None,
                     names=['height', 'gender'])
df1= pd.DataFrame(data)
df1

FileNotFoundError: [Errno 2] No such file or directory: 'height.xlsx'

In [210]:
cars = {'make': ['Hyundai', 'Kia', 'Ford', 'Chevrolet'],
        'model': ['Sonata', 'K5', 'Taurus', 'Impala'],
        'price': [3200,3100,3500,3700]}
df3 = pd.DataFrame(cars)
export_excel = df3.to_excel('cars.xlsx', index=None, header=True)

In [211]:
a = "abc"
print(len(a))
print(a[1])

3
b


In [212]:
x,y,z = a
print(x)

a


In [213]:
bb = 'A test string'
blist0 = bb.split()
blist1 = bb.split('i')
print(blist0, blist1)

['A', 'test', 'string'] ['A test str', 'ng']


In [214]:
aa = a + "ABC"
print(aa)

abcABC


In [215]:
aaa = a*3
print(aaa)

abcabcabc


In [216]:
mystr = 'abcdeabcab'
n0 = mystr.count('ab')
n1 = mystr.find('ab')
n2 = mystr.rfind('ab')
newstr = mystr.replace('ab', 'AB')
print(n0, n1, n2, newstr)

3 0 8 ABcdeABcAB


In [217]:
import re
mystr = re.sub('\\[','A', '[12.5+13-1*5$')
print(mystr)

A12.5+13-1*5$


In [218]:
mtstr = re.sub('[a-z]', '-', 'bcde0123ABC')
print(mtstr)

----0123ABC


In [219]:
l_case = re.search('[a-z]', 'bcde0123ABC')
if l_case: print('a-z exits')
else: print('No a-z')

a-z exits


In [220]:
l_case = re.search('[k-z]', 'bcde0123ABC')
if l_case: print('k-z exits')
else: print('No k-z')

No k-z


In [221]:
mystr = [re.sub('grey|gray', 'GRAY',word) for word in ['grey', 'gray', 'groy', 'greay', 'greey']]
print(mystr)

['GRAY', 'GRAY', 'groy', 'greay', 'greey']


In [222]:
mystr = [re.sub('gr(e|a)y', 'GRAY',word) for word in ['grey', 'gray', 'groy', 'greay', 'greey']]
print(mystr)

['GRAY', 'GRAY', 'groy', 'greay', 'greey']


In [223]:
pip install pandas

In [224]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [225]:
s = Series([10,20,30], index=['a', 'b', 'c']); s

a    10
b    20
c    30
dtype: int64

In [226]:
df=DataFrame(s, columns=["A"]); df

A
a  10
b  20
c  30

In [227]:
s.__class__

pandas.core.series.Series

In [228]:
df.__class__

pandas.core.frame.DataFrame

In [229]:
s.to_numpy()

array([10, 20, 30])

In [230]:
df.to_numpy()

array([[10],
       [20],
       [30]])

In [231]:
s.to_numpy().shape

(3,)

In [232]:
df.to_numpy().shape

(3, 1)

In [233]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [234]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [235]:
df.columns

Index(['A'], dtype='object')

In [236]:
d = {'one': Series([1,2], index=['a', 'b']),
     'two': Series([1,2,3], index=['a', 'b', 'c'])}
df = DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  NaN    3

In [237]:
x = np.arange(4).reshape(2,2)
df=DataFrame(x)
df.columns=["A", "B"]
df.index=[11,12]
df

A  B
11  0  1
12  2  3

In [238]:
from google.colab import files
uploaded = files.upload()

In [239]:
from pandas import read_csv

faithful = read_csv('faithful.csv')

faithful.__class__
faithful.shape
faithful.to_csv('old_faithful.csv')

In [241]:
import statsmodels.api as sm
trees = sm.datasets.get_rdataset("trees")['data']
mtcars = sm.datasets.get_rdataset("mtcars")['data']
iris = sm.datasets.get_rdataset("iris")['data']

In [244]:
trees.__class__
mtcars.__class__
iris.__class__

pandas.core.frame.DataFrame

In [268]:
s1 = Series([1.0, 2, 3])
sa = Series([1.0, 2, 3], index=['a', 'b', 'c'])
sc = Series([0.0, 1, 2], index=['a', 'b', 'd'])
sn = Series([1,2,1,3,3,5,3,4])
print(s1)
print(s1-2)
print(sa)
print(sc)
sac = sa+sc; print(sac)

0    1.0
1    2.0
2    3.0
dtype: float64
0   -1.0
1    0.0
2    1.0
dtype: float64
a    1.0
b    2.0
c    3.0
dtype: float64
a    0.0
b    1.0
d    2.0
dtype: float64
a    1.0
b    3.0
c    NaN
d    NaN
dtype: float64


In [261]:
sac.isnull()

a    False
b    False
c     True
d     True
dtype: bool

In [262]:
sac.notnull()

a     True
b     True
c    False
d    False
dtype: bool

In [263]:
sac.fillna(-1.0)

a    1.0
b    3.0
c   -1.0
d   -1.0
dtype: float64

In [264]:
sx=sac.dropna(); sx

a    1.0
b    3.0
dtype: float64

In [265]:
sy=pd.concat([sx, sc[:2]]);sy

a    1.0
b    3.0
a    0.0
b    1.0
dtype: float64

In [266]:
sy.drop('a')

b    3.0
b    1.0
dtype: float64

In [269]:
sn.head()

0    1
1    2
2    1
3    3
4    3
dtype: int64

In [270]:
sn.describe()

count    8.00000
mean     2.75000
std      1.38873
min      1.00000
25%      1.75000
50%      3.00000
75%      3.25000
max      5.00000
dtype: float64

In [271]:
list(sn.unique())

[1, 2, 3, 5, 4]

In [272]:
sn.nunique()

5

In [273]:
sn.replace([1,2],0)

0    0
1    0
2    0
3    3
4    3
5    5
6    3
7    4
dtype: int64